# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Introduction to Web Development
author: Lara Burton
copyright: "2023"
logo: images/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

parse:
  myst_enable_extensions:
    - deflist
    - html_admonition

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/lsburtonBYU/web-book
  path_to_book: main
  branch: gh-pages

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: images/favicon.ico
  baseurl: https://lsburtonbyu.github.io/web-book/intro.html
  use_issues_button: true
  use_repository_button: true
