title: Introduction to Web Development
author: Lara Burton
copyright: "2023"
logo: images/logo.png
only_build_toc_files: true

execute:
  execute_notebooks: auto

parse:
  myst_enable_extensions:
    - deflist
    - html_admonition
    - smartquotes

sphinx:
  # config:
  #   html_theme_options:
  #     use_sidenotes: true
  extra_extensions:
    - sphinx_exercise
    - sphinx_togglebutton

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/lsburtonBYU/web-book
  path_to_book: main
  branch: gh-pages

html:
  favicon: images/favicon.ico
  baseurl: https://lsburtonbyu.github.io/web-book/
  use_issues_button: true
  use_repository_button: true
  use_multitoc_numbering: true
